import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useContext } from "react";
import Menu from "../components/Menu";
import styles from "../styles/Home.module.css";
import { UserContext } from "../utils/UserContext";

//this is the shop page
const Home = ({ products }) => {
    const [user, setUser] = useContext(UserContext);
    const buyNow = (id) => {
        const buy = fetch(`http://localhost:5000/api/orders/`, {
            method: "POST",
            credentials: "include",
            headers: {
                Accept: "application/json",
                "Content-Type": "application/json",
                //add authorization header
                Authorization: `Bearer ${user.token}`,
            },
            body: JSON.stringify({ id }),
        });
    };
    return (
        <div className={styles.container}>
            <Head>
                <title>Shop Page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Menu />

                <p className={styles.description}>
                    Get started by editing{" "}
                    <code className={styles.code}>pages/index.js</code>
                </p>

                <div className={styles.grid}>
                    {products.map((product) => (
                        <div className={styles.card} key={product.id}>
                            <Link href={`/products/${product._id}`} passHref>
                                <h3>{product.name}</h3>
                            </Link>
                            <p>{product.description}</p>
                            <p>{product.price}</p>
                            <button
                                className="buy-now"
                                onClick={() => buyNow(product._id)}
                            >
                                Buy Now
                            </button>
                        </div>
                    ))}
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://qoddi.com"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by <span className={styles.logo}>Qoddi</span>
                </a>
            </footer>
        </div>
    );
};

export default Home;

export const getStaticProps = async (context) => {
    const response = await fetch("http://localhost:5000/api/products/", {
        method: "GET",
    });

    const res = await response.json();

    const products = res.data.data ? res.data.data : [];

    return { props: { products }, revalidate: 1 };
};
